# Create Cheeses
sharp_cheddar = Cheese.create!(name:"Sharp Cheddar")
camembert = Cheese.create!(name:"Camembert")
brie = Cheese.create!(name:"Brie")
gruyere = Cheese.create!(name:"Gruyere")
gorgonzola = Cheese.create!(name:"Gorgonzola")
wensleydale = Cheese.create!(name:"Wensleydale")
roquefort = Cheese.create!(name:"Roquefort")
appenzellar = Cheese.create!(name:"Appenzellar")
challerhocker = Cheese.create!(name:"Challerhocker")
raclette = Cheese.create!(name:"Raclette")
triple_creme = Cheese.create!(name:"Triple Creme")
asiago = Cheese.create!(name:"Asiago")
blue = Cheese.create!(name:"Blue - General")
blue_cheddar = Cheese.create!(name:"Blue Cheddar")
mild_cheddar = Cheese.create!(name:"Mild Cheddar")
chevre = Cheese.create!(name:"Chevre")
colby = Cheese.create!(name:"Colby")
comte = Cheese.create!(name:"Comte")
feta = Cheese.create!(name:"Feta")
aged_gouda = Cheese.create!(name:"Aged Gouda")
smoked_gouda = Cheese.create!(name:"Smoked Gouda")
young_gouda = Cheese.create!(name:"Young Gouda")
havarti = Cheese.create!(name:"Havarti")
limburger = Cheese.create!(name:"Limburger")
monterey_jack = Cheese.create!(name:"Monterey Jack")
muenster = Cheese.create!(name:"Muenster")
munster = Cheese.create!(name:"Myzithra")
parm = Cheese.create!(name:"Parmiggiano-Reggiano / Parmesan")
provolone = Cheese.create!(name:"Provolone")
romano = Cheese.create!(name:"Pecorino Romano")
swiss = Cheese.create!(name:"Mild Swiss")
fontina = Cheese.create!(name:"Fontina")
edam = Cheese.create!(name:"Edam")
emmental = Cheese.create!(name:"Emmental")
mozz = Cheese.create!(name:"Mozzarella")
ossau = Cheese.create!(name:"Ossau-Iraty")
epoisses = Cheese.create!(name:"Epoisses")
taleggio = Cheese.create!(name:"Taleggio")
leicester = Cheese.create!(name:"Red Leicester")
cheshire = Cheese.create!(name:"Cheshire")
gloucester = Cheese.create!(name:"Gloucester")
morbier = Cheese.create!(name:"Morbier")
pepper_jack = Cheese.create!(name:"Pepper Jack")
idiazabal = Cheese.create!(name:"Idiazabal")
dubliner = Cheese.create!(name:"Dubliner")

# Create Beers
Beer.create!(name:"Ale - General")
Beer.create!(name:"Stout")
Beer.create!(name:"IPA / India Pale Ale")
Beer.create!(name:"Pilsner")
Beer.create!(name:"Porter")
Beer.create!(name:"Wheat Beer")
Beer.create!(name:"Brown Ale")
Beer.create!(name:"Bitter")
Beer.create!(name:"Bock")
Beer.create!(name:"Saison")
Beer.create!(name:"Biere de Garde")
Beer.create!(name:"Dunkel")
Beer.create!(name:"Gueuze")
Beer.create!(name:"Weissbier")
Beer.create!(name:"Doppelbock")
Beer.create!(name:"Dubbel")
Beer.create!(name:"Scotch Ale")
Beer.create!(name:"Kolsch")
Beer.create!(name:"Blonde Ale")
Beer.create!(name:"Pale Ale")
Beer.create!(name:"Altbier")
Beer.create!(name:"Amber Lager")
Beer.create!(name:"Hefeweizen")
Beer.create!(name:"Lambic")
Beer.create!(name:"Imperial Stout")
Beer.create!(name:"Rauchbier")
Beer.create!(name:"Weissbock")
Beer.create!(name:"Barley Wine")
Beer.create!(name:"Helles")
Beer.create!(name:"Abbey")
Beer.create!(name:"Trappist")
marzen = Beer.create!(name:"Marzen")
Beer.create!(name:"Old Ale")

# Create pairings
sharp_cheddar.pairings.create!(beer: Beer.find_by(name: "Barley Wine"))
sharp_cheddar.pairings.create!(beer: Beer.find_by(name: "Weissbier"))
sharp_cheddar.pairings.create!(beer: Beer.find_by(name: "Gueuze"))
sharp_cheddar.pairings.create!(beer: Beer.find_by(name: "Imperial Stout"))
sharp_cheddar.pairings.create!(beer: Beer.find_by(name: "Lambic"))
sharp_cheddar.pairings.create!(beer: Beer.find_by(name: "IPA / India Pale Ale"))
sharp_cheddar.pairings.create!(beer: Beer.find_by(name: "Pale Ale"))
sharp_cheddar.pairings.create!(beer: Beer.find_by(name: "Pilsner"))
sharp_cheddar.pairings.create!(beer: Beer.find_by(name: "Rauchbier"))
camembert.pairings.create!(beer: Beer.find_by(name: "Altbier"))
camembert.pairings.create!(beer: Beer.find_by(name: "Bock"))
camembert.pairings.create!(beer: Beer.find_by(name: "Brown Ale"))
camembert.pairings.create!(beer: Beer.find_by(name: "Doppelbock"))
camembert.pairings.create!(beer: Beer.find_by(name: "Pale Ale"))
camembert.pairings.create!(beer: Beer.find_by(name: "Saison"))
camembert.pairings.create!(beer: Beer.find_by(name: "Kolsch"))
brie.pairings.create!(beer: Beer.find_by(name: "Doppelbock"))
brie.pairings.create!(beer: Beer.find_by(name: "Dubbel"))
brie.pairings.create!(beer: Beer.find_by(name: "Gueuze"))
brie.pairings.create!(beer: Beer.find_by(name: "Helles"))
brie.pairings.create!(beer: Beer.find_by(name: "Old Ale"))
brie.pairings.create!(beer: Beer.find_by(name: "Scotch Ale"))
brie.pairings.create!(beer: Beer.find_by(name: "Kolsch"))
brie.pairings.create!(beer: Beer.find_by(name: "Biere de Garde"))
brie.pairings.create!(beer: Beer.find_by(name: "Blonde Ale"))
gruyere.pairings.create!(beer: Beer.find_by(name: "Bock"))
gruyere.pairings.create!(beer: Beer.find_by(name: "Porter"))
gruyere.pairings.create!(beer: Beer.find_by(name: "Dunkel"))
gorgonzola.pairings.create!(beer: Beer.find_by(name: "Barley Wine"))
gorgonzola.pairings.create!(beer: Beer.find_by(name: "Dubbel"))
gorgonzola.pairings.create!(beer: Beer.find_by(name: "IPA / India Pale Ale"))
gorgonzola.pairings.create!(beer: Beer.find_by(name: "Lambic"))
gorgonzola.pairings.create!(beer: Beer.find_by(name: "Saison"))
wensleydale.pairings.create!(beer: Beer.find_by(name: "Ale - General"))
wensleydale.pairings.create!(beer: Beer.find_by(name: "Blonde Ale"))
wensleydale.pairings.create!(beer: Beer.find_by(name: "Pale Ale"))
roquefort.pairings.create!(beer: Beer.find_by(name: "Barley Wine"))
roquefort.pairings.create!(beer: Beer.find_by(name: "Dubbel"))
roquefort.pairings.create!(beer: Beer.find_by(name: "IPA / India Pale Ale"))
roquefort.pairings.create!(beer: Beer.find_by(name: "Saison"))
roquefort.pairings.create!(beer: Beer.find_by(name: "Lambic"))
appenzellar.pairings.create!(beer: Beer.find_by(name: "Bock"))
appenzellar.pairings.create!(beer: Beer.find_by(name: "Doppelbock"))
appenzellar.pairings.create!(beer: Beer.find_by(name: "Pale Ale"))
challerhocker.pairings.create!(beer: Beer.find_by(name: "Bock"))
challerhocker.pairings.create!(beer: Beer.find_by(name: "Doppelbock"))
challerhocker.pairings.create!(beer: Beer.find_by(name: "Pale Ale"))
raclette.pairings.create!(beer: Beer.find_by(name: "Lambic"))
raclette.pairings.create!(beer: Beer.find_by(name: "Hefeweizen"))
raclette.pairings.create!(beer: Beer.find_by(name: "Saison"))
triple_creme.pairings.create!(beer: Beer.find_by(name: "Abbey"))
triple_creme.pairings.create!(beer: Beer.find_by(name: "Trappist"))
triple_creme.pairings.create!(beer: Beer.find_by(name: "Porter"))
asiago.pairings.create!(beer: Beer.find_by(name: "Biere de Garde"))
asiago.pairings.create!(beer: Beer.find_by(name: "Brown Ale"))
asiago.pairings.create!(beer: Beer.find_by(name: "Dunkel"))
asiago.pairings.create!(beer: Beer.find_by(name: "Lambic"))
asiago.pairings.create!(beer: Beer.find_by(name: "IPA / India Pale Ale"))
asiago.pairings.create!(beer: Beer.find_by(name: "Saison"))
blue.pairings.create!(beer: Beer.find_by(name: "Gueuze"))
blue.pairings.create!(beer: Beer.find_by(name: "IPA / India Pale Ale"))
blue.pairings.create!(beer: Beer.find_by(name: "Pale Ale"))
blue.pairings.create!(beer: Beer.find_by(name: "Pilsner"))
blue.pairings.create!(beer: Beer.find_by(name: "Rauchbier"))
blue.pairings.create!(beer: Beer.find_by(name: "Weissbier"))
blue.pairings.create!(beer: Beer.find_or_create_by(name: "Red Ale"))
blue_cheddar.pairings.create!(beer: Beer.find_by(name: "Barley Wine"))
blue_cheddar.pairings.create!(beer: Beer.find_by(name: "IPA / India Pale Ale"))
blue_cheddar.pairings.create!(beer: Beer.find_by(name: "Pale Ale"))
blue_cheddar.pairings.create!(beer: Beer.find_by(name: "Red Ale"))
mild_cheddar.pairings.create!(beer: Beer.find_by(name: "Pilsner"))
mild_cheddar.pairings.create!(beer: Beer.find_by(name: "Amber Lager"))
chevre.pairings.create!(beer: Beer.find_by(name: "Hefeweizen"))
chevre.pairings.create!(beer: Beer.find_by(name: "Lambic"))
chevre.pairings.create!(beer: Beer.find_by(name: "Weissbock"))
chevre.pairings.create!(beer: Beer.find_by(name: "Wheat Beer"))
colby.pairings.create!(beer: Beer.find_by(name: "Biere de Garde"))
colby.pairings.create!(beer: Beer.find_by(name: "Brown Ale"))
colby.pairings.create!(beer: Beer.find_by(name: "Dunkel"))
colby.pairings.create!(beer: Beer.find_by(name: "Saison"))
comte.pairings.create!(beer: Beer.find_by(name: "Bock"))
comte.pairings.create!(beer: Beer.find_by(name: "Porter"))
comte.pairings.create!(beer: Beer.find_by(name: "Dunkel"))
feta.pairings.create!(beer: Beer.find_by(name: "Biere de Garde"))
feta.pairings.create!(beer: Beer.find_by(name: "Hefeweizen"))
feta.pairings.create!(beer: Beer.find_by(name: "Pale Ale"))
feta.pairings.create!(beer: Beer.find_by(name: "Weissbier"))
feta.pairings.create!(beer: Beer.find_by(name: "Wheat Beer"))
aged_gouda.pairings.create!(beer: Beer.find_by(name: "Brown Ale"))
aged_gouda.pairings.create!(beer: Beer.find_by(name: "Helles"))
aged_gouda.pairings.create!(beer: Beer.find_by(name: "Imperial Stout"))
smoked_gouda.pairings.create!(beer: Beer.find_by(name: "Doppelbock"))
smoked_gouda.pairings.create!(beer: Beer.find_by(name: "Old Ale"))
smoked_gouda.pairings.create!(beer: Beer.find_by(name: "Weissbier"))
young_gouda.pairings.create!(beer: Beer.find_by(name: "Biere de Garde"))
young_gouda.pairings.create!(beer: Beer.find_by(name: "Hefeweizen"))
havarti.pairings.create!(beer: Beer.find_by(name: "Doppelbock"))
havarti.pairings.create!(beer: Beer.find_by(name: "Pilsner"))
havarti.pairings.create!(beer: Beer.find_by(name: "Scotch Ale"))
limburger.pairings.create!(beer: Beer.find_by(name: "Barley Wine"))
limburger.pairings.create!(beer: Beer.find_by(name: "Lambic"))
limburger.pairings.create!(beer: Beer.find_by(name: "Saison"))
monterey_jack.pairings.create!(beer: Beer.find_by(name: "Kolsch"))
monterey_jack.pairings.create!(beer: Beer.find_by(name: "Pilsner"))
monterey_jack.pairings.create!(beer: Beer.find_by(name: "Amber Lager"))
muenster.pairings.create!(beer: Beer.find_by(name: "Pilsner"))
muenster.pairings.create!(beer: Beer.find_or_create_by(name: "Red Ale"))
munster.pairings.create!(beer: Beer.find_by(name: "Barley Wine"))
munster.pairings.create!(beer: Beer.find_by(name: "Dubbel"))
munster.pairings.create!(beer: Beer.find_by(name: "Saison"))
parm.pairings.create!(beer: Beer.find_by(name: "Amber Lager"))
parm.pairings.create!(beer: Beer.find_by(name: "Brown Ale"))
parm.pairings.create!(beer: Beer.find_by(name: "Imperial Stout"))
parm.pairings.create!(beer: Beer.find_or_create_by(name: "ESB"))
provolone.pairings.create!(beer: Beer.find_by(name: "Pale Ale"))
provolone.pairings.create!(beer: Beer.find_or_create_by(name: "Belgian White"))
romano.pairings.create!(beer: Beer.find_by(name: "Pale Ale"))
romano.pairings.create!(beer: Beer.find_by(name: "Trappist"))
swiss.pairings.create!(beer: Beer.find_by(name: "Doppelbock"))
swiss.pairings.create!(beer: Beer.find_by(name: "Old Ale"))
swiss.pairings.create!(beer: Beer.find_or_create_by(name: "Dortmunder"))
swiss.pairings.create!(beer: Beer.find_or_create_by(name: "Weissbock"))
fontina.pairings.create!(beer: Beer.find_by(name: "Altbier"))
fontina.pairings.create!(beer: Beer.find_or_create_by(name: "Oatmeal Stout"))
fontina.pairings.create!(beer: Beer.find_or_create_by(name: "American Pale Ale"))
edam.pairings.create!(beer: Beer.find_by(name: "American Pale Ale"))
edam.pairings.create!(beer: Beer.find_by(name: "Hefeweizen"))
edam.pairings.create!(beer: Beer.find_by(name: "IPA / India Pale Ale"))
edam.pairings.create!(beer: Beer.find_by(name: "Bitter"))
emmental.pairings.create!(beer: Beer.find_by(name: "Doppelbock"))
emmental.pairings.create!(beer: Beer.find_by(name: "Old Ale"))
emmental.pairings.create!(beer: Beer.find_by(name: "Dortmunder"))
mozz.pairings.create!(beer: Beer.find_by(name: "Saison"))
mozz.pairings.create!(beer: Beer.find_by(name: "Trappist"))
ossau.pairings.create!(beer: Beer.find_by(name: "Stout"))
ossau.pairings.create!(beer: Beer.find_by(name: "Barley Wine"))
ossau.pairings.create!(beer: Beer.find_by(name: "Porter"))
epoisses.pairings.create!(beer: Beer.find_by(name: "Belgian White"))
epoisses.pairings.create!(beer: Beer.find_by(name: "Bitter"))
epoisses.pairings.create!(beer: Beer.find_or_create_by(name: "Sour Ale"))
taleggio.pairings.create!(beer: Beer.find_by(name: "Belgian White"))
taleggio.pairings.create!(beer: Beer.find_by(name: "Bitter"))
taleggio.pairings.create!(beer: Beer.find_by(name: "Sour Ale"))
leicester.pairings.create!(beer: Beer.find_by(name: "Bitter"))
leicester.pairings.create!(beer: Beer.find_or_create_by(name: "ESB"))
leicester.pairings.create!(beer: Beer.find_by(name: "Pale Ale"))
cheshire.pairings.create!(beer: Beer.find_by(name: "Bitter"))
cheshire.pairings.create!(beer: Beer.find_by(name: "Pale Ale"))
gloucester.pairings.create!(beer: Beer.find_by(name: "Brown Ale"))
gloucester.pairings.create!(beer: Beer.find_by(name: "Ale - General"))
gloucester.pairings.create!(beer: Beer.find_by(name: "Bitter"))
morbier.pairings.create!(beer: Beer.find_by(name: "Saison"))
morbier.pairings.create!(beer: Beer.find_by(name: "Ale - General"))
morbier.pairings.create!(beer: Beer.find_by(name: "Abbey"))
pepper_jack.pairings.create!(beer: Beer.find_by(name: "Blonde Ale"))
pepper_jack.pairings.create!(beer: Beer.find_by(name: "American Pale Ale"))
pepper_jack.pairings.create!(beer: Beer.find_by(name: "Belgian White"))
pepper_jack.pairings.create!(beer: Beer.find_by(name: "Pilsner"))
idiazabal.pairings.create!(beer: Beer.find_by(name: "Brown Ale"))
idiazabal.pairings.create!(beer: Beer.find_by(name: "Helles"))
idiazabal.pairings.create!(beer: Beer.find_by(name: "Biere de Garde"))
idiazabal.pairings.create!(beer: Beer.find_by(name: "American Pale Ale"))
dubliner.pairings.create!(beer: Beer.find_by(name: "Stout"))
dubliner.pairings.create!(beer: Beer.find_by(name: "Oatmeal Stout"))
marzen.pairings.create!(cheese: Cheese.find_by(name: "Challerhocker"))
marzen.pairings.create!(cheese: Cheese.find_by(name: "Raclette"))
marzen.pairings.create!(cheese: Cheese.find_by(name: "Appenzellar"))
marzen.pairings.create!(cheese: Cheese.find_by(name: "Comte"))

puts "Seed finished"
puts "#{Cheese.count} cheeses created!"
puts "#{Beer.count} beers created!"
puts "#{Pairing.count} pairings created!"


u = User.new
u.email = 'logangingerich@yahoo.com'
u.password = 'password'
u.password_confirmation = 'password'
u.save
